<?php

use \Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_FORM_ID_alter().
 */
function handyphrases_blocks_form_node_phrase_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $account = \Drupal::currentUser();
  $roles = $account->getRoles();

  if (!in_array('administrator', $roles) ) {
    unset($form['field_category']);
    unset($form['field_spanish']);
  }

}

