<?php

/**
 * @file
 * Contains handyphrases.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function handyphrases_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the handyphrases module.
    case 'help.page.handyphrases':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom functionality for HandyPhrases website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function handyphrases_theme() {
  return array(
    'translation_item' => array(
      'variables' => array('nid' => NULL, 'translation' => NULL, 'upvotes' => NULL, 'downvotes' => NULL, 'timestamp' => NULL, 'disabled' => NULL),
    ),
    'vote' => array(
      'variables' => array('vote' => NULL, 'uid' => NULL, 'timestamp' => NULL),
    ),
  );
}

/**
 * Implements hook_form_ID_alter().
 */
function handyphrases_form_node_phrase_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['title']['widget'][0]['value']['#title'] = t('Phrase');
  $form['title']['widget'][0]['value']['#description'] = t('Phrase in English. Limited to 255 characters.');
}


/**
 * Implements hook_form_ID_alter().
 */
function handyphrases_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-phrases-translated-phrases') {
    $form['title']['#size'] = 30;
    $form['field_tags_target_id']['#size'] = 30;
  }
}
