<?php

/**
 * @file
 * Contains handyphrases.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function handyphrases_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the handyphrases module.
    case 'help.page.handyphrases':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom functionality for HandyPhrases website.') . '</p>';
      return $output;

    default:
  }
}
