features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
logo:
  use_default: false
  path: themes/custom/zircon/logo.png
favicon:
  use_default: false
  path: ''
